server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/delivery
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration